// shf_core_model.h
// Auto-generated by ml_validation/scripts/export_shf_pinn_to_c.py
// Source: train_pinn_real.py (PINN, lambda_phys=0.30), real bench data
// (C:\jupyter\notebook\ml_validation\data\real_thermal_runs.csv)
//
// Predicts T_core [degC] from (T_ambient, T_room) via a 2-input,
// degree-2 polynomial regressor (5 features + bias = 6 weights),
// trained with a physics-residual loss (lumped 1-node RC model:
// q = G_hat*(T_ambient-T_core), dT_core/dt = (q-(T_core-T_room)/R_loss)/C_hat)
// where R_loss is FIXED (not self-calibrated) to R_motor=0.0115 degC/W --
// see docs/motor_thermal_resistance_estimation.md (Labvolt 8960 datasheet,
// 350W nominal, steady-state dT=a+R*P regression, R^2=0.96).
//
// Validated accuracy: MAE=0.508 degC, RMSE=0.593 degC on ENTIRELY UNSEEN
// 75%/150% motor-load bench runs (interpolation test within 0-200% range) --
// best of 3 variants tried (data-only, free-R_loss PINN, this anchored PINN --
// run `python train_pinn_real.py` for the exact numbers from one seeded run;
// exact MAE has ~0.04 degC run-to-run jitter from un-reset torch RNG state
// between successive train() calls, ranking is stable across reruns).
// Trained with only 1 labeled run out of 5 training runs (physics loss used
// the other 4 runs' T_ambient/T_room with no T_core label) -- this mirrors
// deployment, where T_core is never available outside the lab bench.
//
// Cross-check that passed: this run's fitted C_hat=100026.0 J/degC falls INSIDE
// [86226, 119730] J/degC, the range independently implied by tau/R_motor from
// fit_motor_thermal_resistance.py's per-run exponential fits (tau=991-1377s) --
// i.e. two unrelated methods (transient curve fit vs steady-state power calc)
// agree, which is why R_loss is now trusted as a fixed anchor instead of free.
//
// !! UNVERIFIED ON THIS HARDWARE / TARGET !!
//   - Trained on motor-bench thermistor data, NOT on IN-GPS AS6221 probes.
//   - Assumes physical placement convention: TH1 (temp1) = probe ON/NEAR the
//     monitored equipment surface (T_ambient role), TH2 (temp2) = probe placed
//     away from the heat source as a room/ambient reference (T_room role).
//     If both AS6221 probes are mounted on the equipment itself, this model's
//     inputs do not match its training distribution -- re-validate before use.
//   - R_loss=0.0115 degC/W and C_hat=100026.0 J/degC are now real, cross-checked
//     units -- but G_hat=0.000074 is not (T_ambient was never a real power input,
//     it's a correlated proxy signal; G_hat decayed toward ~0 during training,
//     meaning the R/C relaxation term is doing most of the physics-loss work).
//   - No on-device (ESP32-S3) accuracy/latency measurement has been done yet.
//   - NOT WIRED IN: this header is not yet #included or called from
//     app_main.c / any sensor pipeline. Integration point (mfg_data field
//     vs. local threshold-only use) still needs a decision -- see conversation.

#ifndef SHF_CORE_MODEL_H
#define SHF_CORE_MODEL_H

#define SHF_TA_MEAN 34.23415756f
#define SHF_TA_STD  4.45577335f
#define SHF_TR_MEAN 26.60572815f
#define SHF_TR_STD  0.25277081f

// [Ta, Tr, Ta^2, Ta*Tr, Tr^2] -> T_core, on z-scored (Ta,Tr)
#define SHF_W_TA    5.00167942f
#define SHF_W_TR    -0.07222717f
#define SHF_W_TA2   -0.33325517f
#define SHF_W_TATR  -0.01079761f
#define SHF_W_TR2   0.00046592f
#define SHF_BIAS    40.51256561f

/**
 * @brief Estimate equipment core temperature from two AS6221 readings.
 * @param t_ambient_c  TH1 (probe on/near the monitored equipment surface), degC.
 * @param t_room_c     TH2 (probe placed away as ambient/room reference), degC.
 * @return Estimated core temperature, degC. See file header for validated
 *         accuracy (MAE/RMSE) and placement-convention caveats.
 */
static inline float shf_predict_core_temp(float t_ambient_c, float t_room_c)
{
    float ta = (t_ambient_c - SHF_TA_MEAN) / SHF_TA_STD;
    float tr = (t_room_c    - SHF_TR_MEAN) / SHF_TR_STD;

    return SHF_W_TA   * ta
         + SHF_W_TR   * tr
         + SHF_W_TA2  * ta * ta
         + SHF_W_TATR * ta * tr
         + SHF_W_TR2  * tr * tr
         + SHF_BIAS;
}

#endif // SHF_CORE_MODEL_H
