"""
export_shf_pinn_to_c.py
IN-GPS capstone -- export the trained SHF/PINN core-temperature regressor
(train_pinn_real.py, R_loss-ANCHORED PINN variant) to a standalone C header
for ESP32-S3.

2026-08-26 update: exports variant (C) -- R_loss fixed to the Labvolt-8960-
anchored R_motor=0.0115 degC/W (see docs/motor_thermal_resistance_estimation.md)
-- instead of the earlier free-R_loss variant, because it is now the best of
all three on held-out 75%/150% load runs (MAE=0.543 degC vs 0.585 free-R /
0.732 data-only) AND its C_hat converged to 100027 J/degC, which independently
falls inside the tau/R_motor sanity range [86226, 119730] computed by
fit_motor_thermal_resistance.py -- i.e. two unrelated methods agree, not just
"whatever number the optimizer landed on". See train_pinn_real.py main()'s
printed RESULT block for the full three-way comparison.

Writes the regressor's 6 weights + 4 normalization constants as plain
#define floats, plus a ready-to-call inference function. The physics
constants (G_hat, R_loss, C_hat) are training-time-only (no T_ambient/T_room
-> T_core inference path needs them) and are NOT exported -- only recorded
as a comment for provenance.

Usage: python export_shf_pinn_to_c.py
Output: ../output/shf_core_model.h
"""

import numpy as np
import torch

import train_pinn_real as pr

OUT_PATH = "../output/shf_core_model.h"


def main():
    df = pr.load_data()
    labeled_runs, unlabeled_runs, val_runs = pr.split_runs(df)

    model, phys, pred_v, Tc_v, mae, rmse = pr.train(
        df, labeled_runs, unlabeled_runs, val_runs,
        lambda_phys=pr.LAMBDA_PHYS, label="export",
        fixed_r_loss=pr.R_MOTOR_ANCHOR, init_G=50.0, init_C=100000.0, n_epochs=30000,
    )

    sd = model.state_dict()
    ta_mean = float(sd["ta_mean"]); ta_std = float(sd["ta_std"])
    tr_mean = float(sd["tr_mean"]); tr_std = float(sd["tr_std"])
    W = sd["linear.weight"].detach().numpy().ravel()  # [w_ta, w_tr, w_ta2, w_tatr, w_tr2]
    b = float(sd["linear.bias"].item())

    print(f"exported model: MAE={mae:.3f} degC  RMSE={rmse:.3f} degC "
          f"(held-out 75%/150% load, see train_pinn_real.py)")
    print(f"weights: {W}  bias={b}")
    print(f"norm: ta_mean={ta_mean:.4f} ta_std={ta_std:.4f} "
          f"tr_mean={tr_mean:.4f} tr_std={tr_std:.4f}")
    print(f"physics constants (training-time only, not exported): "
          f"G_hat={phys.G.item():.4f} R_loss={phys.R_loss.item():.4f} C_hat={phys.C_hat.item():.4f}")

    lines = [
        "// shf_core_model.h",
        "// Auto-generated by ml_validation/scripts/export_shf_pinn_to_c.py",
        "// Source: train_pinn_real.py (PINN, lambda_phys=%.2f), real bench data" % pr.LAMBDA_PHYS,
        "// (C:\\jupyter\\notebook\\ml_validation\\data\\real_thermal_runs.csv)",
        "//",
        "// Predicts T_core [degC] from (T_ambient, T_room) via a 2-input,",
        "// degree-2 polynomial regressor (5 features + bias = 6 weights),",
        "// trained with a physics-residual loss (lumped 1-node RC model:",
        "// q = G_hat*(T_ambient-T_core), dT_core/dt = (q-(T_core-T_room)/R_loss)/C_hat)",
        "// where R_loss is FIXED (not self-calibrated) to R_motor=%.4f degC/W --" % pr.R_MOTOR_ANCHOR,
        "// see docs/motor_thermal_resistance_estimation.md (Labvolt 8960 datasheet,",
        "// 350W nominal, steady-state dT=a+R*P regression, R^2=0.96).",
        "//",
        "// Validated accuracy: MAE=%.3f degC, RMSE=%.3f degC on ENTIRELY UNSEEN" % (mae, rmse),
        "// 75%/150% motor-load bench runs (interpolation test within 0-200% range) --",
        "// best of 3 variants tried (data-only, free-R_loss PINN, this anchored PINN --",
        "// run `python train_pinn_real.py` for the exact numbers from one seeded run;",
        "// exact MAE has ~0.04 degC run-to-run jitter from un-reset torch RNG state",
        "// between successive train() calls, ranking is stable across reruns).",
        "// Trained with only 1 labeled run out of 5 training runs (physics loss used",
        "// the other 4 runs' T_ambient/T_room with no T_core label) -- this mirrors",
        "// deployment, where T_core is never available outside the lab bench.",
        "//",
        "// Cross-check that passed: this run's fitted C_hat=%.1f J/degC falls INSIDE" % phys.C_hat.item(),
        "// [86226, 119730] J/degC, the range independently implied by tau/R_motor from",
        "// fit_motor_thermal_resistance.py's per-run exponential fits (tau=991-1377s) --",
        "// i.e. two unrelated methods (transient curve fit vs steady-state power calc)",
        "// agree, which is why R_loss is now trusted as a fixed anchor instead of free.",
        "//",
        "// !! UNVERIFIED ON THIS HARDWARE / TARGET !!",
        "//   - Trained on motor-bench thermistor data, NOT on IN-GPS AS6221 probes.",
        "//   - Assumes physical placement convention: TH1 (temp1) = probe ON/NEAR the",
        "//     monitored equipment surface (T_ambient role), TH2 (temp2) = probe placed",
        "//     away from the heat source as a room/ambient reference (T_room role).",
        "//     If both AS6221 probes are mounted on the equipment itself, this model's",
        "//     inputs do not match its training distribution -- re-validate before use.",
        "//   - R_loss=%.4f degC/W and C_hat=%.1f J/degC are now real, cross-checked" % (phys.R_loss.item(), phys.C_hat.item()),
        "//     units -- but G_hat=%.6f is not (T_ambient was never a real power input," % phys.G.item(),
        "//     it's a correlated proxy signal; G_hat decayed toward ~0 during training,",
        "//     meaning the R/C relaxation term is doing most of the physics-loss work).",
        "//   - No on-device (ESP32-S3) accuracy/latency measurement has been done yet.",
        "",
        "#ifndef SHF_CORE_MODEL_H",
        "#define SHF_CORE_MODEL_H",
        "",
        f"#define SHF_TA_MEAN {ta_mean:.8f}f",
        f"#define SHF_TA_STD  {ta_std:.8f}f",
        f"#define SHF_TR_MEAN {tr_mean:.8f}f",
        f"#define SHF_TR_STD  {tr_std:.8f}f",
        "",
        "// [Ta, Tr, Ta^2, Ta*Tr, Tr^2] -> T_core, on z-scored (Ta,Tr)",
        f"#define SHF_W_TA    {W[0]:.8f}f",
        f"#define SHF_W_TR    {W[1]:.8f}f",
        f"#define SHF_W_TA2   {W[2]:.8f}f",
        f"#define SHF_W_TATR  {W[3]:.8f}f",
        f"#define SHF_W_TR2   {W[4]:.8f}f",
        f"#define SHF_BIAS    {b:.8f}f",
        "",
        "/**",
        " * @brief Estimate equipment core temperature from two AS6221 readings.",
        " * @param t_ambient_c  TH1 (probe on/near the monitored equipment surface), degC.",
        " * @param t_room_c     TH2 (probe placed away as ambient/room reference), degC.",
        " * @return Estimated core temperature, degC. See file header for validated",
        " *         accuracy (MAE/RMSE) and placement-convention caveats.",
        " */",
        "static inline float shf_predict_core_temp(float t_ambient_c, float t_room_c)",
        "{",
        "    float ta = (t_ambient_c - SHF_TA_MEAN) / SHF_TA_STD;",
        "    float tr = (t_room_c    - SHF_TR_MEAN) / SHF_TR_STD;",
        "",
        "    return SHF_W_TA   * ta",
        "         + SHF_W_TR   * tr",
        "         + SHF_W_TA2  * ta * ta",
        "         + SHF_W_TATR * ta * tr",
        "         + SHF_W_TR2  * tr * tr",
        "         + SHF_BIAS;",
        "}",
        "",
        "#endif // SHF_CORE_MODEL_H",
        "",
    ]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
