"""
export_to_c.py
학습된 모델 파라미터를 ESP32용 C 헤더(model_params.h)로 변환
"""

import numpy as np
import joblib
import os

MODEL_PATH = "../output/final_model.pkl"
HEADER_PATH = "../output/model_params.h"


def export_header(model, path: str):
    lines = [
        "// model_params.h",
        "// Auto-generated by export_to_c.py",
        "// Target: ESP32",
        "",
        "#ifndef MODEL_PARAMS_H",
        "#define MODEL_PARAMS_H",
        "",
    ]

    # TODO: 모델 종류에 따라 파라미터 추출 로직 구현
    # 예시: Decision Tree / Random Forest threshold, feature index 등
    # lines.append(f"#define N_FEATURES {n_features}")

    lines += ["", "#endif // MODEL_PARAMS_H", ""]

    with open(path, "w") as f:
        f.write("\n".join(lines))

    print(f"헤더 파일 생성 완료: {path}")


def main():
    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"모델 파일을 찾을 수 없습니다: {MODEL_PATH}")

    model = joblib.load(MODEL_PATH)
    export_header(model, HEADER_PATH)


if __name__ == "__main__":
    main()
